### PR TITLE
Sfp 401 params

### PR DESCRIPTION
**Pull request by hansvancalster**
Fully parameterize the protocol.

### CODE REVIEW

**Comment by hansvancalster** [comment]
@ElsDeBie I'm still working on this, but you can take a look already.

**Comment by ElsDeBie** [comment]
Where does this branch fit in sfp 401? Should I work on this branch (in some text chapter 7 - stappenplan are still some 3 * 3 m instead of parameters). Sorry, lost again :see_no_evil:

**Comment by hansvancalster** [comment]
I don't have time to work on it now, but I will merge this branch in your branch `sfp-401` so you can continue work in that branch.  Before you continue, don't forget to Pull the changes.

**Comment by ElsDeBie** [comment]
Super! Thanks Hans

**Pull request merged**
