### PR TITLE
Sfp 401 patches

### PR DESCRIPTION
**Pull request by hansvancalster**
Several improvements and things that needed to be changed because we changed the sfp templates in package `protocolhelper`.

A difficult issue is the cover scales. The problem is that the various sorts of cover scales are not stored in an appropriate way in the database. There is a lot of missing information about cover scales. The database essentially only stores the name of the scale, the cover codes and a percent cover value (midpoint). However, for each cover-code we should have `percent_lower_bound`, `percent_upper_bound`, `abundance_lower_bound` and `abundance_upper_bound` (the latter two only for combined cover-abundance scales and can be NA).

### CODE REVIEW

**Comment by hansvancalster** [comment]
@ElsDeBie note that this PR wants to merge branch `sfp-401-patches` (the one that is discussed here) into your branch `sfp-401`.
Best contact me if you have local changes in `sfp-401` which have not yet been pushed to the remote.

**Comment by ElsDeBie** [comment]
> @ElsDeBie note that this PR wants to merge branch `sfp-401-patches` (the one that is discussed here) into your branch `sfp-401`.
> Best contact me if you have local changes in `sfp-401` which have not yet been pushed to the remote.

>>> C:/Program Files/Git/bin/git.exe checkout sfp-401
Your branch is up to date with 'origin/sfp-401'.
So you can merge and I will pull afterwards when I start working here again.

**Comment by hansvancalster** [comment]
> A difficult issue is the cover scales. The problem is that the various sorts of cover scales are not stored in an appropriate way in the database. There is a lot of missing information about cover scales. The database essentially only stores the name of the scale, the cover codes and a percent cover value (midpoint). However, for each cover-code we should have `percent_lower_bound`, `percent_upper_bound`, `abundance_lower_bound` and `abundance_upper_bound` (the latter two only for combined cover-abundance scales and can be NA).

Some more info why I think this is needed: to fully parameterize the protocol, we need this information to programmatically show about the details of a cover scale in a table. Secondly, percent midpoints are traditionally used for analyzing cover-scales, but more recent techniques allow to analyze such data more appropriately using censoring techniques (i.e. we observe a value between `percent_lower_bound` and `percent_upper_bound` (we do not observe the midpoint)). 

Something to discuss with @JoLoos

**Comment by ElsDeBie** [comment]
This means that the hard core of INBOVEG has to be changed ... we have to discuss that with team 'Databeheer'. Do you have an idea if these techniques are often used. And can't this be solved by using the original code to convert to the asked parameters as a quick solution?

**Comment by florisvdh** [comment]
Technical sidenote about:

> C:/Program Files/Git/bin/git.exe checkout sfp-401
Your branch is up to date with 'origin/sfp-401'.

Only after a `git fetch` will `origin/sfp-401` (your _local_ pointer to the remote branch) be updated to actually reflect the remote. So unfortunately the statement 'is up to date' may mislead (although strictly it is correct). The output of `git fetch` (if any) will show which origin/** branches become updated in that way. `git fetch` is also executed by a `git pull`. The main difference with local branches is that 'remote' origin/** branches cannot be worked on directly.

**Comment by hansvancalster** [comment]
@ElsDeBie another thing: is there a reason you restricted to Londo and Braun-Blanquet? I would think that any cover scale could potentially be used?

**Comment by hansvancalster** [comment]
> This means that the hard core of INBOVEG has to be changed ... we have to discuss that with team 'Databeheer'. Do you have an idea if these techniques are often used. 

Surely not often, but the other reason is just as important (making the protocol more generic / parameterized)

> And can't this be solved by using the original code to convert to the asked parameters as a quick solution?

We can make a table ourselves with these data and put that table under version control in this repo; but I would prefer such important data (they really define the observations) are stored in the database. That would be useful also for the LSVI package, the HabNorm project, etc.

**Comment by ElsDeBie** [comment]
of course but on the short term, this can be a temporary solution. Changing the inboveg-database is not just adding some columns I guess. But I suggest I will mention it already on the inboveg-meeting 26/03.

**Comment by ElsDeBie** [comment]
Yes, these are the most detailed coverscales. But as mentioned in the protocol, in "Bijlage 1 INBO-defaultwaarden en projectfiche" projectvalues can be entered who are not the default values in the protocol; This to prevent that many different scales will be used for vegetationanalyses;

**Comment by hansvancalster** [comment]
> Yes, these are the most detailed coverscales. But as mentioned in the protocol, in "Bijlage 1 INBO-defaultwaarden en projectfiche" projectvalues can be entered who are not the default values in the protocol; This to prevent that many different scales will be used for vegetationanalyses;

Good that you point to that table. We might want to rethink and fully parameterize that. I also need to explain to you the way we are going to implement project-specific versus thematic protocols. But it is easier if I can do that in a meeting.

**Pull request merged**
